version: '3'
services:
  frontend:
    build:
      context: './frontend'
    ports:
      - "8080:80"
  backend:
    build:
      context: './backend'
    ports:
      - '3000:3000'
    environment:
      - GOOGLE_MAPS_API_KEY
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - '/usr/local/mongo/data/db:/data/db'
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD
